### ISSUE TITLE
Exception when used in combination with sphinxcontrib-spelling

### ISSUE THREAD

**Issue by staalb** [useblocks/sphinx-data-viewer#14]
The sphinx-data-viewer extension throws an exception when running the spelling checker from sphinxcontrib-spelling. The following error is produced when running `make spelling`:
```
Extension error (sphinx_data_viewer.sphinx_data_viewer):
Handler <function install_lib_static_files at 0x7f63c586d260> for event 'env-updated' threw an exception (exception: 'SpellingBuilder' object has no attribute 'script_files')
```

This only happens when using sphinx-data-viewer version 0.1.3 in combination with recent versions of Sphinx tooling. This is a fragment of my `Pipfile`:
```
[packages]
sphinx = "==7.2.6"
sphinxcontrib-spelling = "==8.0.0"
sphinx-needs = "==2.0.0"
sphinxcontrib-plantuml = "==0.27"
```
When sphinx-data-viewer is downgraded to version 0.1.2 the error disappears.

Output when running `sphinx-build` with `-v`:
```
$ make spelling
Running Sphinx v7.2.0
Initializing Spelling Checker 8.0.0
making output directory... done
locale_dir /home/user/doc/locales/en/LC_MESSAGES does not exist
Ignoring wiki words
Ignoring acronyms
Ignoring Python builtins
Ignoring importable module names
Ignoring contributor names
Looking for custom word list in /home/user/doc/spelling_wordlist.txt
Scanning contributors
locale_dir /home/user/doc/locales/en/LC_MESSAGES does not exist
building [mo]: targets for 0 po files that are out of date
writing output... 
building [spelling]: all documents
updating environment: locale_dir /home/user/doc/locales/en/LC_MESSAGES does not exist
[new config] 8 added, 0 changed, 0 removed
reading sources... [ 12%] hardware/hdd
reading sources... [ 25%] hardware/hrs
reading sources... [ 38%] hardware/hts
reading sources... [ 50%] index
reading sources... [ 62%] software/sdd
reading sources... [ 75%] software/srs
reading sources... [ 88%] system/ssdd
reading sources... [100%] system/ssrs


Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx/events.py", line 96, in emit
    results.append(listener.handler(self.app, *args))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx_data_viewer/sphinx_data_viewer.py", line 68, in install_lib_static_files
    if extra_path.endswith("js") and str(web_path) not in app.builder.script_files:
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SpellingBuilder' object has no attribute 'script_files'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx/application.py", line 354, in build
    self.builder.build_update()
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 290, in build_update
    self.build(['__all__'], to_build)
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 426, in read
    for retval in self.events.emit('env-updated', self.env):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/share/virtualenvs/doc-_SZa7Qpc/lib/python3.11/site-packages/sphinx/events.py", line 107, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function install_lib_static_files at 0x7f5120210f40> for event 'env-updated' threw an exception (exception: 'SpellingBuilder' object has no attribute 'script_files')

Extension error (sphinx_data_viewer.sphinx_data_viewer):
Handler <function install_lib_static_files at 0x7f5120210f40> for event 'env-updated' threw an exception (exception: 'SpellingBuilder' object has no attribute 'script_files')
make: *** [Makefile:27: spelling] Error 2
```

**Comment by danwos** [comment]
Thanks for the detailed error report. :+1: 

It is fixed by checking the current builder and its capability to register js/css files.
